# Generated by Django 3.2.4 on 2021-07-13 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_on']},
        ),
    ]
