# Generated by Django 3.2.4 on 2021-07-19 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0002_remove_snippet_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='slug',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
    ]
