# Generated by Django 3.2.4 on 2021-07-20 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urlshortener', '0002_shortener_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shortener',
            name='author',
        ),
    ]
